// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: laboratory.proto

package pb_grpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_laboratory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_laboratory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_laboratory_proto_rawDescGZIP(), []int{0}
}

type BoxSpecification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int32 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width  int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Depth  int32 `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
}

func (x *BoxSpecification) Reset() {
	*x = BoxSpecification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_laboratory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoxSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxSpecification) ProtoMessage() {}

func (x *BoxSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_laboratory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxSpecification.ProtoReflect.Descriptor instead.
func (*BoxSpecification) Descriptor() ([]byte, []int) {
	return file_laboratory_proto_rawDescGZIP(), []int{1}
}

func (x *BoxSpecification) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BoxSpecification) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoxSpecification) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type Box struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Volume int32 `protobuf:"varint,1,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *Box) Reset() {
	*x = Box{}
	if protoimpl.UnsafeEnabled {
		mi := &file_laboratory_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Box) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Box) ProtoMessage() {}

func (x *Box) ProtoReflect() protoreflect.Message {
	mi := &file_laboratory_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Box.ProtoReflect.Descriptor instead.
func (*Box) Descriptor() ([]byte, []int) {
	return file_laboratory_proto_rawDescGZIP(), []int{2}
}

func (x *Box) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

var File_laboratory_proto protoreflect.FileDescriptor

var file_laboratory_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x56, 0x0a, 0x10, 0x42,
	0x6f, 0x78, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x65,
	0x70, 0x74, 0x68, 0x22, 0x1d, 0x0a, 0x03, 0x42, 0x6f, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x32, 0x35, 0x0a, 0x0d, 0x42, 0x6f, 0x78, 0x4c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x24, 0x0a, 0x07, 0x4d, 0x61, 0x6b, 0x65, 0x42, 0x6f, 0x78, 0x12, 0x11,
	0x2e, 0x42, 0x6f, 0x78, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x04, 0x2e, 0x42, 0x6f, 0x78, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x70,
	0x62, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_laboratory_proto_rawDescOnce sync.Once
	file_laboratory_proto_rawDescData = file_laboratory_proto_rawDesc
)

func file_laboratory_proto_rawDescGZIP() []byte {
	file_laboratory_proto_rawDescOnce.Do(func() {
		file_laboratory_proto_rawDescData = protoimpl.X.CompressGZIP(file_laboratory_proto_rawDescData)
	})
	return file_laboratory_proto_rawDescData
}

var file_laboratory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_laboratory_proto_goTypes = []interface{}{
	(*Empty)(nil),            // 0: Empty
	(*BoxSpecification)(nil), // 1: BoxSpecification
	(*Box)(nil),              // 2: Box
}
var file_laboratory_proto_depIdxs = []int32{
	1, // 0: BoxLaboratory.MakeBox:input_type -> BoxSpecification
	2, // 1: BoxLaboratory.MakeBox:output_type -> Box
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_laboratory_proto_init() }
func file_laboratory_proto_init() {
	if File_laboratory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_laboratory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_laboratory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoxSpecification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_laboratory_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Box); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_laboratory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_laboratory_proto_goTypes,
		DependencyIndexes: file_laboratory_proto_depIdxs,
		MessageInfos:      file_laboratory_proto_msgTypes,
	}.Build()
	File_laboratory_proto = out.File
	file_laboratory_proto_rawDesc = nil
	file_laboratory_proto_goTypes = nil
	file_laboratory_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BoxLaboratoryClient is the client API for BoxLaboratory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BoxLaboratoryClient interface {
	MakeBox(ctx context.Context, in *BoxSpecification, opts ...grpc.CallOption) (*Box, error)
}

type boxLaboratoryClient struct {
	cc grpc.ClientConnInterface
}

func NewBoxLaboratoryClient(cc grpc.ClientConnInterface) BoxLaboratoryClient {
	return &boxLaboratoryClient{cc}
}

func (c *boxLaboratoryClient) MakeBox(ctx context.Context, in *BoxSpecification, opts ...grpc.CallOption) (*Box, error) {
	out := new(Box)
	err := c.cc.Invoke(ctx, "/BoxLaboratory/MakeBox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoxLaboratoryServer is the server API for BoxLaboratory service.
type BoxLaboratoryServer interface {
	MakeBox(context.Context, *BoxSpecification) (*Box, error)
}

// UnimplementedBoxLaboratoryServer can be embedded to have forward compatible implementations.
type UnimplementedBoxLaboratoryServer struct {
}

func (*UnimplementedBoxLaboratoryServer) MakeBox(context.Context, *BoxSpecification) (*Box, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeBox not implemented")
}

func RegisterBoxLaboratoryServer(s *grpc.Server, srv BoxLaboratoryServer) {
	s.RegisterService(&_BoxLaboratory_serviceDesc, srv)
}

func _BoxLaboratory_MakeBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoxSpecification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxLaboratoryServer).MakeBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BoxLaboratory/MakeBox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxLaboratoryServer).MakeBox(ctx, req.(*BoxSpecification))
	}
	return interceptor(ctx, in, info, handler)
}

var _BoxLaboratory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BoxLaboratory",
	HandlerType: (*BoxLaboratoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeBox",
			Handler:    _BoxLaboratory_MakeBox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "laboratory.proto",
}
